<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.campusoverflow</groupId>
        <artifactId>campus-overflow</artifactId>
        <version>0.1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>co-discovery</artifactId>
    <packaging>pom</packaging>
    <name>CampusOverflow :: Discovery 内容发现</name>
    <modules>
        <module>co-discovery-api</module>
        <module>co-discovery-domain</module>
        <module>co-discovery-application</module>
        <module>co-discovery-infrastructure</module>
        <module>co-discovery-interfaces</module>
    </modules>
</project>
